backend:
  name: github
  branch: main
  # FIXME:  Replace before prod
  repo: saralain/nw-idolfest-website-cms-fork
  # FIXME: Find and replace nw-idolfest-website-cms-fork anywhere it appears
  cms_label_prefix: web-editor/
  # Comment this next line out to use this locally
  base_url: https://c03m0wt68h.execute-api.us-east-1.amazonaws.com
  auth_endpoint: /auth
# FIXME: Swap these for prod
site_url: https://saralain.github.io/nw-idolfest-website-cms-fork
site_domain: saralain.github.io
# site_url: https://nwidolfest.com/
# FIXME: Swap with the below once deploying
logo_url: https://nwidolfest.com/static/8556a9b691450f2853f5e49679ae87bf/ff82a/Logo%20Pink.webp
# logo_url: https://nwidolfest.com/admin/logo.svg
# This is where it's stored in the repo
media_folder: "/static/images/uploads"
# This is where it is url-wise
public_folder: "/images/uploads"
collections: 
  - name: "blog-posts"
    label: "Blog Entries (2023)"
    label_singular: "Blog Entry"
    # NOTE: This needs to be updated for each event to make blogs work
    folder: "src/markdown-pages/blog/2023"
    create: true
    delete: true
    summary: "{{fields.title}} ({{fields.date}})"
    slug: "{{slug}}" # (    o_o) slug
    sort: 'date:desc'
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD"}
      - {label: "Template", name: "template", widget: "hidden", default: "blogpost"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "root-pages"
    label: "Top-Level Pages"
    label_singular: "Top-Level Page"
    folder: "src/markdown-pages/"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "about"
    label: "About Section Pages"
    label_singular: "About Section Page"
    folder: "src/markdown-pages/about"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events"
    label: "Events Section Pages"
    label_singular: "Events Section Page"
    folder: "src/markdown-pages/events"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "guests"
    # FIXME: Needs images
    label: "Guests"
    label_singular: "Guest"
    folder: "src/markdown-pages/guests/2023"
    create: true
    delete: true
    slug: "{{slug}}" # (     o_O) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "guest"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Descriptor", name: "descriptor", widget: "string"}
      - {label: "Twitch", name: "twitch", widget: "string"}
      - {label: "Youtube", name: "youtube", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - {label: "Homepage", name: "homepage", widget: "string"}
      - {label: "Instagram", name: "instagram", widget: "string"}
      - {label: "Bandcamp", name: "bandcamp", widget: "string"}
      - {label: "Spotify", name: "spotify", widget: "string"}
      - {label: "Facebook", name: "facebook", widget: "string"}
      - {label: "Patreon", name: "patreon", widget: "string"}
      - {label: "Note", name: "NOTE", widget: "hidden", default: "Make sure image of the guest is in the media folder, named guest_(YEAR)_(GUEST_SLUG).png"}

      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Site Settings & Navigation"
    name: "general"
    files: 
    - label: "Site Metadata"
      name: "site-metadata"
      file: "siteMetadata.json"
      extension: "json"
      description: "General Site Settings"
      fields:
        - {label: "Global title", name: "title", widget: "string"}
        - {label: "Short Dates", name: "shortDates", widget: "string"}
        - {label: "Long Dates", name: "longDates", widget: "string"}
        - {label: "Location", name: "location", widget: "string"}
        - label: Social
          name: social
          widget: object
          fields: 
            - {label: "Twitter", name: "twitter", widget: "string"}
            - {label: "Facebook", name: "facebook", widget: "string"}
            - {label: "Instagram", name: "instagram", widget: "string"}
            - {label: "Discord", name: "discord", widget: "string"}
            - {label: "Email", name: "email", widget: "string"}
    - label: "Navigation Items"
      label_singular: "Navigation Item"
      name: "navigation"
      file: "src/components/HeaderData.json"
      extension: "json"
      description: "Items to show in site navigation"
      fields: 
        - label: "Navigation Items"
          label_singular: "Navigation Item"
          name: "headersData"
          widget: "list"
          fields: 
            - {label: Label, name: label, widget: string}
            - {label: "Page path (short - example: /register or /guests/phoebe)", name: href, widget: string}
            - {label: "Hidden from Navigation", name: disabled, widget: boolean, required: false}
            - {label: "Link is to outside website (eg google docs)", name: external, widget: boolean, required: false}
            - label: Child Navigation Items
              label_singular: Child Navigation Item
              name: children
              widget: list
              fields: 
              - {label: Label, name: label, widget: string}
              - {label: "Page path (short - example: /register or /guests/phoebe)", name: href, widget: string}
              - {label: "Hidden from Navigation", name: disabled, widget: boolean, required: false}
              - {label: "Link is to outside website (eg google docs)", name: external, widget: boolean, required: false}
